(()=>{const $=s=>document.querySelector(s),crops=window.CROPS;let crop=crops[1],trials=[],streak=0;
function buttons(){const box=$("#crops");crops.forEach(c=>{let b=document.createElement("button");b.className="crop"+(c.id===crop.id?" active":"");b.innerHTML="<span>"+c.icon+"</span>"+c.name;b.addEventListener("click",()=>{crop=c;[...box.children].forEach(x=>x.classList.remove("active"));b.classList.add("active")});box.appendChild(b)})}
function bind(id,fmt){let e=$("#"+id),o=$("#"+id+"Out");e.addEventListener("input",()=>o.textContent=fmt(+e.value))}
bind("sun",v=>v+" hr/day");bind("water",v=>v.toFixed(1)+" in/week");bind("ph",v=>v.toFixed(1));bind("temp",v=>v+"°F");
const lightScore=(actual,target)=>{const n={Low:0,Medium:1,High:2};return Math.max(.15,1-Math.abs(n[actual]-n[target])*.42)};
function rangeScore(v,good,ideal){if(v>=ideal[0]&&v<=ideal[1])return 1;if(v>=good[0]&&v<=good[1]){let edge=v<ideal[0]?ideal[0]-v:v-ideal[1],span=v<ideal[0]?ideal[0]-good[0]:good[1]-ideal[1];return .65+.35*(1-edge/(span||1))}let d=v<good[0]?good[0]-v:v-good[1],span=Math.max(good[1]-good[0],1);return Math.max(.05,.6-d/span)}
function quality(n){return n>=.9?"Excellent":n>=.75?"Good":n>=.55?"Fair":n>=.35?"Poor":"Severely stressed"}
function run(){let vals={light:$("#light").value,sun:+$("#sun").value,water:+$("#water").value,ph:+$("#ph").value,temp:+$("#temp").value};
let s={light:lightScore(vals.light,crop.light),sun:rangeScore(vals.sun,crop.sun,crop.ideal.sun),water:rangeScore(vals.water,crop.water,crop.ideal.water),ph:rangeScore(vals.ph,crop.ph,crop.ideal.ph),temp:rangeScore(vals.temp,crop.temp,crop.ideal.temp)};
let limiting=Math.min(...Object.values(s)),geo=Math.pow(Object.values(s).reduce((a,b)=>a*b,1),1/5);let base=(.58*geo+.42*limiting)*100;let jitter=((trials.length*17+crop.name.length*11)%7)-3;let y=Math.max(2,Math.min(100,Math.round(base+jitter)));
let obs=[];if(s.light<.72||s.sun<.72)obs.push("Growth pattern suggests the crop may not be receiving enough usable light.");if(s.water<.72)obs.push(vals.water<crop.ideal.water[0]?"Leaves show signs consistent with moisture stress.":"Excess moisture is reducing root-zone performance and produce quality.");if(s.ph<.72)obs.push("Nutrient uptake appears limited even though other conditions may be favorable.");if(s.temp<.72)obs.push(vals.temp<crop.ideal.temp[0]?"Development is slow under the current temperature.":"Heat stress is interfering with normal crop development.");if(!obs.length)obs.push("The crop is vigorous and producing consistently under these conditions.");if(y>=90)obs.push("Marketable production is close to the model's maximum for this crop.");
$("#empty").hidden=true;$("#result").hidden=false;$("#yield").textContent=y+"%";$("#meter").style.width=y+"%";$("#health").textContent=quality((s.water+s.ph+s.temp)/3);$("#growth").textContent=quality((s.light+s.sun+s.water+s.temp)/4);$("#produce").textContent=quality((s.light+s.sun+s.water+s.ph+s.temp)/5);streak=y>=90?streak+1:0;$("#reliability").textContent=streak>=3?"Goal met!":streak+"/3 high-yield";$("#observations").innerHTML=obs.map(x=>"<li>"+x+"</li>").join("");
trials.push({...vals,crop:crop.name,y});renderLog()}
function renderLog(){let l=$("#log");l.innerHTML=trials.map((t,i)=>"<tr><td>"+(i+1)+"</td><td>"+t.crop+"</td><td>"+t.light+"</td><td>"+t.sun+" hr</td><td>"+t.water.toFixed(1)+'"</td><td>'+t.ph.toFixed(1)+"</td><td>"+t.temp+"°F</td><td><b>"+t.y+"%</b></td></tr>").join("")}
document.querySelectorAll(".tip").forEach(btn=>{btn.addEventListener("click",()=>{const box=$("#tipbox"),same=box.dataset.for===btn.getAttribute("aria-label")&&!box.hidden;document.querySelectorAll(".tip").forEach(x=>x.setAttribute("aria-expanded","false"));if(same){box.hidden=true;box.dataset.for="";return}box.textContent=btn.dataset.tip;box.hidden=false;box.dataset.for=btn.getAttribute("aria-label");btn.setAttribute("aria-expanded","true")})});
$("#run").addEventListener("click",run);$("#reset").addEventListener("click",()=>{trials=[];streak=0;$("#result").hidden=true;$("#empty").hidden=false;$("#log").innerHTML='<tr><td colspan="8" class="muted">No trials yet.</td></tr>'});
$("#sources").innerHTML=crops.map(c=>'<div class="source-card"><b>'+c.icon+" "+c.name+"</b> — "+c.source+' · <a href="'+c.url+'" target="_blank" rel="noopener">View research source ↗</a></div>').join("");buttons()})();