window.CROPS=[
{id:"avocado",name:"Avocado",icon:"🥑",light:"High",sun:[6,10],water:[1.2,2.1],ph:[5.5,7.0],temp:[60,85],ideal:{sun:[8,10],water:[1.5,2],ph:[6,6.5],temp:[65,80]},source:"UC Agriculture & Natural Resources",url:"https://ipm.ucanr.edu/home-and-landscape/cultural-tips-for-growing-avocado/"},
{id:"tomato",name:"Tomato",icon:"🍅",light:"High",sun:[6,12],water:[.8,1.6],ph:[5.8,6.8],temp:[60,90],ideal:{sun:[8,10],water:[1,1.5],ph:[6.2,6.8],temp:[70,80]},source:"Penn State Extension",url:"https://extension.psu.edu/tomato-production"},
{id:"strawberry",name:"Strawberry",icon:"🍓",light:"High",sun:[6,12],water:[1,2],ph:[5.3,6.5],temp:[45,85],ideal:{sun:[8,10],water:[1,1.5],ph:[5.8,6.5],temp:[60,75]},source:"University of Minnesota Extension",url:"https://extension.umn.edu/fruit/growing-strawberries-home-garden"},
{id:"watermelon",name:"Watermelon",icon:"🍉",light:"High",sun:[6,12],water:[.7,2],ph:[5.8,6.6],temp:[65,95],ideal:{sun:[8,10],water:[1,1.5],ph:[6,6.5],temp:[75,90]},source:"Iowa State University Extension",url:"https://yardandgarden.extension.iastate.edu/how-to/growing-watermelon-home-garden"},
{id:"romaine",name:"Romaine Lettuce",icon:"🥬",light:"Medium",sun:[4,8],water:[.8,1.3],ph:[6,6.8],temp:[45,75],ideal:{sun:[5,7],water:[.9,1.1],ph:[6,6.8],temp:[55,65]},source:"University of Minnesota Extension",url:"https://extension.umn.edu/vegetables/growing-lettuce-endive-and-radicchio"},
{id:"pepper",name:"Red Bell Pepper",icon:"🫑",light:"High",sun:[6,12],water:[.8,1.4],ph:[6,7],temp:[60,90],ideal:{sun:[8,10],water:[.9,1.2],ph:[6.2,7],temp:[70,80]},source:"University of Minnesota Extension",url:"https://extension.umn.edu/vegetables/growing-peppers"},
{id:"celery",name:"Celery",icon:"🌱",light:"Medium",sun:[5,9],water:[1.2,2.2],ph:[6,6.8],temp:[50,75],ideal:{sun:[6,8],water:[1.5,2],ph:[6,6.8],temp:[60,70]},source:"Texas A&M AgriLife",url:"https://aggie-horticulture.tamu.edu/vegetable/wp-content/uploads/sites/10/2011/10/celery2.pdf"},
{id:"corn",name:"Sweet Corn",icon:"🌽",light:"High",sun:[6,12],water:[.8,1.6],ph:[5.8,7],temp:[60,95],ideal:{sun:[8,10],water:[1,1.5],ph:[6,6.5],temp:[70,85]},source:"Iowa State University Extension",url:"https://yardandgarden.extension.iastate.edu/how-to/growing-sweet-corn-home-garden"}
];